// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo;

#nullable disable

namespace Modelo.Migrations
{
    [DbContext(typeof(ConexionDatos))] // Cambiado de Context a ConexionDatos
    [Migration("20251109215516_BancoDB")]
    partial class BancoDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Cliente", b =>
            {
                b.Property<int>("UsuarioCodigo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioCodigo"));

                b.Property<string>("PrimerNombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SegundoNombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Documento")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NumeroContacto")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UsuarioCodigo");

                b.ToTable("Clientes");
            });

            modelBuilder.Entity("Entidades.CuentaCorriente", b =>
            {
                b.Property<int>("BilleteraCodigo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BilleteraCodigo"));

                b.Property<int>("UsuarioCodigo")
                    .HasColumnType("int");

                b.Property<decimal>("MontoActual")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("BilleteraCodigo");

                b.HasIndex("UsuarioCodigo");

                b.ToTable("Cuentas");
            });

            modelBuilder.Entity("Entidades.Movimiento", b =>
            {
                b.Property<int>("TransaccionCodigo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionCodigo"));

                b.Property<int>("BilleteraCodigo")
                    .HasColumnType("int");

                b.Property<string>("Detalle")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("FechaOperacion")
                    .HasColumnType("datetime2");

                b.Property<decimal>("Valor")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Categoria")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("TransaccionCodigo");

                b.HasIndex("BilleteraCodigo");

                b.ToTable("Movimientos");
            });

            modelBuilder.Entity("Entidades.CuentaCorriente", b =>
            {
                b.HasOne("Entidades.Cliente", "Cliente")
                    .WithMany("Bolsas") // coincide con la lista en Cliente
                    .HasForeignKey("UsuarioCodigo")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Cliente");
            });

            modelBuilder.Entity("Entidades.Movimiento", b =>
            {
                b.HasOne("Entidades.CuentaCorriente", "CuentaCorriente")
                    .WithMany("Registros") // coincide con la lista en CuentaCorriente
                    .HasForeignKey("BilleteraCodigo")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CuentaCorriente");
            });

            modelBuilder.Entity("Entidades.Cliente", b =>
            {
                b.Navigation("Bolsas");
            });

            modelBuilder.Entity("Entidades.CuentaCorriente", b =>
            {
                b.Navigation("Registros");
            });
#pragma warning restore 612, 618
        }
    }
}
